#! /bin/bash
#
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --array=1-100
MAIN_PATH="$PWD"


START=$SLURM_ARRAY_TASK_ID
NUMLINES=2
STOP=$((SLURM_ARRAY_TASK_ID*NUMLINES))
START="$(($STOP - $(($NUMLINES - 1))))"
echo "START=$START"
echo "STOP=$STOP"

for (( N = $START; N <= $STOP; N++))
do
    LINE=$(sed -n "$N"p sims_param.csv)
    IFS=',' read INDEX INPUT_DIR OUTPUT_DIR ANTENNA_CONFIG COORDINATES SPATIAL_RESOLUTION CENTRAL_FREQUENCY FREQUENCY_RESOLUTION INTEGRATION_TIME MAP_SIZE N_PX<<< "$LINE"
    #INPUT_DIR="$MAIN_PATH/$INPUT_DIR"
    #OUTPUT_DIR="$MAIN_PATH/$OUTPUT_DIR"
    mkdir "$MAIN_PATH/sim_$INDEX"
    #cp antenna_config/alma.cycle9.3.1.cfg $MAIN_PATH/sim_$INDEX
    cd "$MAIN_PATH/sim_$INDEX"
    echo $CONDA_PREFIX
    conda run -n casa6.5 python $MAIN_PATH/alma_simulator.py $INDEX $INPUT_DIR $OUTPUT_DIR "$MAIN_PATH/$ANTENNA_CONFIG" $COORDINATES $SPATIAL_RESOLUTION $CENTRAL_FREQUENCY $FREQUENCY_RESOLUTION $INTEGRATION_TIME $MAP_SIZE $N_PX 
    cd ..
    #rm -r "$MAIN_PATH/sim_$INDEX"
done

