name: Qodana
on:
    workflow_dispatch:
    pull_request:
    push:
        branches: # Specify your branches here
            - development
jobs:
    qodana:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
            checks: write
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
                  fetch-depth: 0  # a full history is required for pull request analysis
            - name: 'Setup Pyenv'
              uses: actions/setup-python@v2
              with:
                  python-version: '3.12.8'
            - name: 'Qodana Scan'
              uses: JetBrains/qodana-action@v2024.3
              with:
                pr-mode: false
                args: --apply-fixes
                push-fixes: pull-request
              env:
                  QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}